#!/bin/sh
tmux new-session -d
tmux split-window -h
tmux select-pane -L
tmux split-window -v -p 20
tmux select-pane -R
tmux split-window -v -p 20
tmux select-pane -L
tmux select-pane -U
tmux -2 attach-session -d
